### ISSUE TITLE
copyright infringement

### ISSUE THREAD

**Issue by ashishhmishra** [krushnajena/food_delivery_system_web_app_customer#1]
Code has been reported under copyright infringement so anyone will try to use this code has to pass through copyright violation law.

**Comment by krushnajena** [comment]
copyright issue has-been closed due to nonpayment of due

**Comment by ashishhmishra** [comment]
> copyright issue has-been closed due to nonpayment of due

paymewnt will not be due to whole month not available and also breaking the company policy.

**Comment by krushnajena** [comment]
did you have shared any company policy to me on my email or skypee or whatsapp or anywhere. This project assumed as a freelance project as any letters or emails not received from your company.

**Comment by krushnajena** [comment]
have you informed me to discontinue the work.

**Comment by krushnajena** [comment]
after trying to reach with your spoke he will not responding. after that i think tied up with a fraud company who wants to work only not to pay.

**Comment by ashishhmishra** [comment]
you haven't notified your plan and it impacted us lot so no issue. do whatever you can. we are planning to notify other companies and it's nothing to do with freelancing.if you are working with private company than you have to follow the rule and i think you can read delivergenie policies. you are not sincere with your work.W will just notify others so they will not be in shit situation what you have created.
please refer this
https://docs.github.com/en/github/site-policy/guide-to-submitting-a-dmca-takedown-notice

**Comment by ashishhmishra** [comment]
> after trying to reach with your spoke he will not responding. after that i think tied up with a fraud company who wants to work only not to pay.

no issue, we have payment transaction for your work

**Comment by krushnajena** [comment]
ok thanks then call me for mutual settlement . i am deleting the repo.

**Comment by ashishhmishra** [comment]
> ok thanks then call me for mutual settlement . i am deleting the repo.

no issue. we are planning to report your behavior in india so others will be cautious working with you and your unethical behavior. I think you are mature enough to understand what  am i talking. after this mess I don't think is any meaning of any call.
